version: '3.8'

services:
  server:
    container_name: server
    ports:
      - "8080:8080"
      - "4444:5555"
    build:
      args:
        APP: server
      context: .
      dockerfile: Dockerfile.server.prod
    env_file:
      - ./.env
    command: >
      sh -c "
        echo 'Starting service...';
        turbo build --no-cache --filter server;
        turbo start --no-cache --filter server;
      "
    depends_on:
      psql:
        condition: service_healthy
  client:
    ports:
      - "3000:3000"
    depends_on:
      - server
    build: 
      args:
        APP: client
      context: .
      dockerfile: Dockerfile.client.prod
    container_name: client
    command: > 
      sh -c "
        turbo build --filter client
        turbo start --filter client
      "
  psql:
    container_name: psql
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data_volume:
