import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "tailwind-config/styles";
import StoreProvider from "../providers/store-provider";
import "./globals.css";
import { SocketProvider } from "@/contexts/socket-context";

import { InviteContainer } from "@/components/invite-container";
import ReactQueryProvider from "@/providers/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ft_transgender",
  description: "Generated by khaliha ela molana team",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className="h-screen w-screen relative">
        <ReactQueryProvider>
          <StoreProvider>
            <SocketProvider>
              <InviteContainer />
              {children}
            </SocketProvider>
          </StoreProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
