import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "tailwind-config/styles";
import AsideBar from "../../layouts/shared-aside-bar/aside-bar";
import BarMobile from "../../layouts/shared-bar-mobile/bar-mobile";
import Header from "../../layouts/shared-haeder/header";
import "../globals.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ft_transcendance",
  description: "Generated by khaliha ela molana team",
};

export default function MenuAsideroutersLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <div className="h-full w-full flex flex-col">
      <Header />
      <ToastContainer />
      <BarMobile />
      <div className="h-full flex flex-row overflow-hidden">
        <AsideBar />
        <main className="w-full">
          {children}
        </main>
      </div>
    </div>
  );
}
